language: php

php:
- 7.0
- 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
- sudo apt-get install libxml2-utils
- composer self-update
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
- phpenv config-rm xdebug.ini
- composer install --no-interaction --prefer-dist --quiet
- php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
- php vendor/bin/phpcs --config-set show_warnings 0

script:
- php vendor/bin/grumphp run
env:
  global:
    secure: DcJb3EOTdOg/y3OeCCb8eP+dSI40G5d+JX0xWw7XZQ5E41id9NGVOnGbzN8Uer0WKfkiailZa/rSbYeISWIESDtMDiWe0dNSPT6xGLOlNdHR39MxDVFP2/QJWscSuW7ajKxNih7Qx+y93oLx73CyxM/H+quHlBL6jpj1j/RpYjIg/oQ7RKvhahI7L0CW337Cre2MfHAVXKNSBRnQPBNFc2OaqWtWb/LBbwj+CmfvdR9I62jxSuqz7Ce/4QpLipqrRTyB/RUbw8bAL0mALWg5jVQQ9DG3iM1iPKsaIKrPkTHbXv1tSx9Td5E1VItpJMXjCgZDjTxq7y++k+QwdVM9K9THDD7eQdlHiHJTEqFUcofZbivNRzlB7NVb46SO1/3BqO/ngp0CG7WcZo7y85QrXRz367KHFoO96FAjKctMmFwmDZkNfuquKFT8hH39qZ/P3eGp9idWoYpj+ADNlc2ALyASkWRfDfg1Zni5FPPBHRAgwAUUe04B8pucDW+1aQyR3GqvWYt2uf1Wt/ocD+Ic/sIp+eRCAGLO7KJZFMcxv4Xf+JuGejw3yD0ezI4MuImsLhUhJftiollDkuBQJaf541A6vNd296WpSBqutl1atduHvh6VAjB9cFYfRe3JM7kTOGWVhR3dTygojTy1yG1eGE4Y3UX0SJqS74aRArtMZew=
